theme: minima
title: folkcoreano
description: hi gays
author:
  name: yonas
  email: "folkcoreano@outlook.com"
minima:
  social_links:
    - {plataform: github, user_url: "https://github.com/folkcoreano"}
    - {plataform: twitter, user_url: "https://twitter.com/folkcoreano"}
    - {plataform: instagram, user_url: "https://instagram.com/folkcoreano"}
  skin: dark
header_pages:
  - about.md
disqus:
  shortname: folkcoreano
