title: folkcoreano
description: hi gays

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  social_links:
    - {plataform: github, user_url: "https://github.com/folkcoreano"}
    - {plataform: twitter, user_url: "https://twitter.com/folkcoreano"}
    - {plataform: instagram, user_url: "https://instagram.com/folkcoreano"}

header_pages:
  - about.md

disqus:
  shortname: folkcoreano
