export default [
  {
    title: "Poetr",
    id: "poetr",
    year: 2023,
    icon: "poetr.svg",
    url: "https://poetr.vercel.app",
    description:
      "Um site para ler poesia, contendo por volta de 24 mil poemas.",
    tags: [
      "pwa",
      "nuxt",
      "vue",
      "tailwind",
      "webworker",
      "indexedb",
      "nuxt-ui",
      "planetscale",
      "mysql",
      "prisma",
      "vercel",
      "typescript",
      "javascript",
      "nodejs",
      "site",
    ],
    position: "top",
  },
  {
    title: "PEPPC",
    id: "peppc",
    year: 2023,
    icon: "peppc.svg",
    url: "https://peppc.vercel.app",
    description:
      "Um site para calcular planos de assinatura de serviços de streaming.",
    tags: [
      "vercel",
      "vue",
      "pwa",
      "imagekit",
      "tailwind",
      "typescript",
      "javascript",
      "nodejs",
      "site",
    ],
    position: "top",
  },
  {
    title: "Baralho Maker",
    id: "editor",
    year: 2023,
    icon: "baralho-maker.svg",
    url: "https://editor.irmaogrande.com",
    description: "Editor de Baralhos para o jogo Irmão Grande & Brasileiro 2.",
    tags: [
      "vue",
      "pwa",
      "indexedb",
      "webworker",
      "vercel",
      "typescript",
      "javascript",
      "nodejs",
      "site",
    ],
    position: "top",
  },
  {
    title: "Roguelator",
    id: "roguelator",
    year: 2023,
    icon: "roguelator.svg",
    url: "https://roguelator.vercel.app",
    description:
      "Uma calculadora porém você precisa escolher o resultado correto. Contém um modo competitivo global apertando 'C' três vezes.",
    tags: [
      "nuxt",
      "vue",
      "postgresql",
      "prisma",
      "vercel",
      "typescript",
      "javascript",
      "nodejs",
      "site",
    ],
    position: "center",
  },
  {
    title: "Cartas Para Quem",
    id: "cartas",
    year: 2023,
    icon: "cartas-para-quem.png",
    url: "https://folkcoreano.itch.io/cartas-para-quem",
    description:
      "Um jogo onde você trabalha como um mago que escreve cartas em uma estação de trem.",
    tags: [
      "aseprite",
      "godot",
      "gdscript",
      "pixelart",
      "jogo",
      "obsidian",
      "itch.io",
    ],
    position: "top",
  },
  {
    title: "OvivimDEX",
    id: "ovidex",
    year: 2023,
    icon: "ovidex.png",
    url: "https://ovidex.deno.dev",
    description: "Um site guia para o jogo Ovivim.",
    tags: [
      "deno",
      "deno-deploy",
      "javascript",
      "typescript",
      "vue",
      "site",
      "imagekit",
    ],
    position: "top",
  },
  {
    title: "Mitski API Rest",
    id: "mitski",
    year: 2022,
    icon: "mitski.svg",
    url: "https://mitski.deno.dev",
    description: "API Rest com músicas da cantora Mitski.",
    tags: [
      "deno",
      "oak",
      "vue",
      "typescript",
      "javascript",
      "deno-deploy",
      "github-actions",
      "site",
      "api",
    ],
    position: "center",
  },
  {
    title: "Phoebe API Rest",
    id: "phoebe",
    year: 2022,
    icon: "phoebe.svg",
    url: "https://phoebe.deno.dev",
    description: "API Rest com músicas da cantora Phoebe Bridgers.",
    tags: [
      "deno",
      "oak",
      "vue",
      "typescript",
      "javascript",
      "deno-deploy",
      "github-actions",
      "site",
      "api",
    ],
    position: "center",
  },
  {
    title: "Manoel API Rest",
    id: "manoel",
    year: 2022,
    icon: "manoel.svg",
    url: "https://manoel.deno.dev",
    description: "API Rest com músicas da cantor Manoel Gomes.",
    tags: [
      "deno",
      "oak",
      "vue",
      "typescript",
      "javascript",
      "deno-deploy",
      "github-actions",
      "site",
      "api",
    ],
    position: "center",
  },
];
